### ISSUE TITLE
Моделди кошируге арналган ссылка истемейди

### ISSUE THREAD

**Issue by zhasulan** [IS2AI/ISSAI_SAIDA_Kazakh_ASR#5]
Жигиттер калайсындар, оте куаныштымын сендердин осындай керек жумыс жасагандарына. Бирак НУ га карайнтын ссылкалар жумыс истемей тур. Сол маселени шешип жиберсениздер. Рахмет

**Comment by mussakhojayeva** [comment]
Здравствуйте,
На данный момент сервер не работает, ожидается поднятие на следующей неделе. Тогда и заработают ссылки.
С уважением, 
Саида
