### ISSUE TITLE
ModuleNotFoundError: No module named 'pandas'

### ISSUE THREAD

**Issue by RyanGuo98** [IS2AI/ISSAI_SAIDA_Kazakh_ASR#6]
hello,I have completed the installation of espnet according to the prompts, and the egs/yesno tests are correct. Then I change the data path according to the prompts in the steps, and run ./run.sh error. I can test import pandas separately. What is the reason for this
stage 0: Setting up directories
Traceback (most recent call last):
  File "local/data_prep.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
torch=1.5.1 cuda=10.1

**Comment by mussakhojayeva** [comment]
Hi. Probably In your espnet environment the pandas are not installed.

**Comment by RyanGuo98** [comment]
> Hi. Probably In your espnet environment the pandas are not installed.

hi,thanks for your reply.i finally find my error.it's in data_prep.py . it's title is #!/usr/bin/env python,but it will use python3.6 in system  env,but my espnet virtual env is python3.7,so i changed it into 3.7,it works. but now i have a new question ,here is exp/make_fbank/*log 

sox FAIL formats: can't open input file `/root/share/data/ISSAI_KSC_335RS_v1.1_flac/Audios/5ed899a15482d.wav': No such file or directory
sox FAIL formats: can't open input  `-': WAVE: RIFF header not found
ERROR (compute-fbank-feats[5.5.1049~1-4592c5]:Read4ByteTag():wave-reader.cc:56) WaveData: expected 4-byte chunk-name, got read error

WARNING (compute-fbank-feats[5.5.1049~1-4592c5]:Read():feat/wave-reader.h:197) Exception caught in WaveHolder::Read(). kaldi::KaldiFatalError
WARNING (compute-fbank-feats[5.5.1049~1-4592c5]:EnsureObjectLoaded():util/kaldi-table-inl.h:317) Failed to load object from 'sox /root/share/data/ISSAI_KSC_335RS_v1.1_flac/Audios/5ed899a15482d.wav -r 16000 -c 1 -b 16 -t wav - downsample | sox -R -t wav - -t wav - rate 16000 dither |'
WARNING (compute-fbank-feats[5.5.1049~1-4592c5]:Close():kaldi-io.cc:515) Pipe sox /root/share/data/ISSAI_KSC_335RS_v1.1_flac/Audios/5ed899a15482d.wav -r 16000 -c 1 -b 16 -t wav - downsample | sox -R -t wav - -t wav - rate 16000 dither | had nonzero return status 512
sox FAIL formats: can't open input file `/root/share/data/ISSAI_KSC_335RS_v1.1_flac/Audios/5ed899aa1a44a.wav': No such file or directory
sox FAIL formats: can't open input  `-': WAVE: RIFF header not found
ERROR (compute-fbank-feats[5.5.1049~1-4592c5]:Read4ByteTag():wave-reader.cc:56) WaveData: expected 4-byte chunk-name, got read error

**Comment by mussakhojayeva** [comment]
Hi, this code was written for the wav version of the dataset previously available. To use the code as it is, you need to convert flac files to wav
