### ISSUE TITLE
Links to the speech data do not work

### ISSUE THREAD

**Issue by cweaver-logitech** [IS2AI/ISSAI_SAIDA_Kazakh_ASR#7]
Hello,

The links to the dataset: [ISSAI_KSC_335RS dataset](https://issai.nu.edu.kz/kz-speech-corpus/) do not resolve...
![image](https://github.com/IS2AI/ISSAI_SAIDA_Kazakh_ASR/assets/87655550/6198e9c5-77a2-4c6c-8b55-dc593a93d9de)

**Comment by mussakhojayeva** [comment]
Hi! We are having some technical works being done, please check the link again little later.

**Comment by cweaver-logitech** [comment]
Thanks

Kind regards,

Chris
